#!/bin/bash
#Snippet that checks for updates of a specific package
#This is just a proof of concept 

package=$1
 

#if mor than one version is installed the first version must not the right version
test $(zypper -n --no-refresh se -s -t package --match-exact $package|grep ^i|awk '{print $7}' | tr -d [:punct:]) -lt $(zypper -n --no-refresh se -s -t package --match-exact --sort-by-name $package | grep ^v|awk '{print $7}'|tr -d [:punct:]|head -1) && new_version="yes" || new_version="no"

if [ "$new_version" == "yes" ]
	then
		echo "there is a newer version available"
		echo "trying to update"
		VENDOR=$(zypper -n --no-refresh se -s -t package --match-exact $package|grep ^v|awk '{print $11}')
		zypper -n --no-refresh in -n --from $VENDOR ${package}
		echo "finished"
	else
		echo "no update available"
fi

exit 0

#zypper -n se -s -t package --match-exact $package|grep ^v|awk '{print $7}'|tr -d [:punct:]
