#!/bin/bash

#git-20102606_2112
#This is cleancheck
#cleancheck is currently under heavly development
#it is expected that things are not working or not
#working probertly although we test it as hard as we
#can.

#As you can see the todo list is quiet long and there will be a long
#time as the final version will be out.

#for bug reporting, please use github bugtracker and commit a fix
#if possible

#for feature requests please use github comments. however there are several
#things here we will never implement. one of them would be support for ubuntu
#because its freaking me out.

#cleancheck.sh
#Script that does several Systemscans.
#It checks system integrety and logs information
#about the system. By default it will do a lot of scans
#and will need a long runtime.
#It creates logfiles which can be inspected aferwards.

##help_option starts here
option_h()
{
echo "$0 [-a PATH] [-c PATH] [-l NAME] [-e DIRS] [-h] [-s PATH] [-w ACDPSU]"
echo "-a set path to clamscan  binary. if not set, which clamscan is used"
echo "-c set path to  chkrootkit binary. if not set /usr/bin/rkhunter is used"
echo "-e exclude these dirs for scanning for viruses"
echo "   you have to seperate the directories by : character"
echo "	 example -e /home/:/media/:/mnt/"
echo "-f pretend to be the firstrun. this is usefull if you update your system"
echo "   and therefore the sha512sums dont match anymore"
echo "   WARNING be sure that you do this only when the system has been updated by rpm"
echo "-l set name and path to logdir"
echo "-h show this help"
echo "-q be as less verbose as possible and log only to logfile"
echo "-s set path to lynis binary. if not set /usr/bin/lynis is used"
echo "-w with feature explizit set feature"
echo "      A: scan for viruses"
echo "      C: check for rootkits"
echo "      D: check health of current disks"
echo "      S: check security holes"
echo "      P: do an package integrety-check. RPMS only"
echo "      U: only update or check the sha512 sums" 
echo "   You may also use this option to set the order of checks performed"
echo "   or to exclude actions that should not be performed."
exit 0	
}
##help option ends here

##setting up runtime varibales starts here

INDEX=$(date +%Y%m%d%H%M%S)

#first initilize the variables
ANTIVIR=
ROOTKIT_CHECKER=
SECURITY_CHECKER=
DISK_CHECKER=
LOGFILE=
USE_QUIET=
FIRST_RUN=
declare -a EXCLUDE_DIRS=
declare -a WITH_FEATURE=
SHA_SUM=/var/log/selftest

option_a()
{
ANTIVIR="$OPTARG"
}

option_c()
{
ROOTKIT_CHECKER="$OPTARG"	
}

option_e()
{
EXCLUDE_DIRS="$OPTARG"
DIRS=$(echo $EXCLUDE_DIRS |  sed "s/:/\n/g" )
}

option_f()
{
FIRST_RUN="yes"	
}

option_l()
{
LOGFILE="$OPTARG"
}

option_q()
{
USE_QUIET="yes"
}

option_s()
{
SECURITY_CHECKER="$OPTARG"	
}

option_w()
{
W_F="$OPTARG"

#convert a contiguous string to an array
#where each letter is an element of the array

c=${#OPTARG}
while [ $c -ge 0 ]
	do
		WITH_FEATURE[$c]=${W_F:$c:1}
		c=$(($c-1))
	done
}



while getopts a:c:l:e:s:w:fhq opt
	do
		case "$opt" in
			a) option_a
			;;
			c) option_c
			;;
			h) option_h
			;;
			l) option_l
			;;
			e) option_e
			;;
			f) option_f
			;;
			s) option_s
			;;
			q) option_q
			;;
			w) option_w
			;;
			\?) option_h #in case of invalid option display help
		esac
	done
shift `expr $OPTIND - 1`

if [ -z $ANTIVIR ]
	then
		ANTIVIR=$(which clamscan || echo "no") #enter the path to clamscan or the path to your virus scanner
fi

if [ -z $ROOTKIT_CHECKER ]
	then
		ROOTKIT_CHECKER=$(which rkhunter || echo "no") #enter the path to your rootkitchecker
fi

if [ -z $SECURITY_CHECKER ] #check for open security holes
	then
		SECURITY_CHECKER=$(which lynis || echo "no")
fi

if [ -z DISK_CHECKER ] #check disk health status
	then
		DISK_CHECKER=$(which smartctl|| echo "no")
fi

if [ -z $USE_QUIET ]
	then
		USE_QUIET="no"
fi

if [ -z $FIRST_RUN ]
	then
		FIRST_RUN="no"
fi

if [ -z $LOGFILE ]
	then
		#to keep the logfile small
		#previous logfiles will be cleared 
		if [ -f /var/log/cleancheck.log ]
			then
				cat /dev/null > /var/log/cleancheck.log
		fi	
		LOGFILE="/var/log/cleancheck.log"
		touch $LOGFILE
	else
		unset LOGDIR
		LOGDIR=$(echo ${LOGFILE%/*} )
		if [ ! -d $LOGDIR ]
			then
				mkdir -p $LOGDIR
		fi
		
		if [ -f $LOGFILE ]
			then
				cat /dev/null > $LOGFILE
		fi
		touch $LOGFILE
fi
##setting up runtime variables ends here


#check whether you are root
check_root()
{
if [ $UID -ne 0 ]
	then 
		drop_failure
		echo "not root"
		exit 1
	else
		main
fi
}

#check whether programs and argumets are set correctly
check_antivir()
{	
echo "checking for Antivirs detection" 2> /dev/null
if [ "$ANTIVIR" == "no" ]
	then
		drop_failure
		echo "An Virus detection tool is not installed."
		echo "trying to get one"
		zypper in clamav clamav-db || we_fail
		ping http://www.clamav.net && freshclam || echo "not possible"
	else
		drop_ok
		echo "trying to update daily.cvd file"
		ping http://www.clamav.net && freshclam || echo "not possible"
fi
}

check_rootkit_checker()
{
echo "checking for rootkit checker" 2> /dev/null
if [ "$ROOTKIT_CHECKER" == "no" ] 
	then
		drop_failure
		echo "A rootkit checker is not installed"
		echo "trying to get one"
		zypper in rkhunter || we_fail
	else
		drop_ok
fi
}

check_lynis()
{
echo "checking for security checker" 2> /dev/null
if [ "$SECURITY_CHECKER" == "no" ]
	then
		drop_failure
		echo "A security checker is not a installed"
		echo "trying to get one"
		zypper in lynis || we_fail
	else
		drop_ok
fi
}

check_smartctl()
{
echo "checking for smartmontools" 2> /dev/null
if [ "$DISK_CHECKER" == "no" ]
	then
		drop_failure
		echo "Smartctl is not installed"
		echo "trying to get it"
		zypper in smartmontools || we_fail
	else
		drop_ok
fi
}

exclude_this() #prepare exclude for clamscan 
{
for dir in  ${DIRS[@]}
	do
		echo \ 
		echo "--exclude-dir"=$dir
	done
}


###Each Action has its own function starts here

#this is the actual scan for viruses using clamscan
virus_scan()
{
if [ ! -z $EXCLUDE_DIRS ]
	then
		if [ "$USE_QUIET" != "no" ]
			then
				{
				echo "with clamscan" 
				echo "with excludedirs"
				echo "Skiping"
								
					for dir in ${DIRS[@]}
						do
							echo $dir
						done
				
				E=$( exclude_this)
				ANT=`$ANTIVIR -r -i --exclude-dir=/proc --exclude-dir=/dev --exclude-dir=/sys  $E /`
				echo "$ANT" 
				} >> $LOGFILE
			else
				{
				echo "with clamscan" 
				echo "with excludedirs"
				echo "Skiping"
								
					for dir in ${DIRS[@]}
						do
							echo $dir
						done
				
				E=$( exclude_this)
				ANT=`$ANTIVIR -r -i --exclude-dir=/proc --exclude-dir=/dev --exclude-dir=/sys $E /`
				echo "$ANT" 
				}|tee -a $LOGFILE
			fi
		else
			if [ "$USE_QUIET" != "no" ]
				then
					{
					echo "with clamscan"
					ANT=`$ANTIVIR -r -i --exclude-dir=/proc --exclude-dir=/dev --exclude-dir=/sys /`
					echo "$ANT" 
					}>> $LOGFILE
				else
					{
					echo "with clamscan"
					ANT=`$ANTIVIR -r -i --exclude-dir=/proc --exclude-dir=/dev --exclude-dir=/sys /`
					echo "$ANT" 
					}|tee -a $LOGFILE
			fi
fi
}


verify_package()
{
is_rpm=$(rpm -q rpm && echo "yes")

if [ "$is_rpm" == "yes" ]
	then
		echo "with rpm package verification"
	else
		echo "package verification for rpm skipped"
fi

}


disk_check()
{
#checking disks using smartmontools	
all_devices=$(ls /dev/sd*) #fixme: check only disks not partitions

for device in $all_devices
	do
		smartctl -H $device
	done
	
}

self_test()
{
SHA512_TEST=$(which sha512sum || echo "no")
SHA512=${SHA512_TEST}

if [ "$SHA512_TEST" = "no"  ]
	then 
		echo "the program for calculating the sha512 sum is not in the system"
		echo "please install it and rerun again"
		exit 1
fi
		
if [ ! -f $SHA_SUM/init/SHA_SUMS ]
	then
		echo "first run of $0. initilize sha512 checksums."
		mkdir -p $SHA_SUM/init
		{
			sha512sum $SHA512
			sha512sum $0
			sha512sum /bin/bash
			sha512sum $ANTIVIR
			sha512sum /usr/bin/freshclam
			sha512sum $ROOTKIT_CHECKER
			sha512sum $SECURITY_CHECKER
			sha512sum /bin/rpm			
		} >> $SHA_SUM/init/SHA_SUMS
		#imutable the SHA_SUMS because this is the weakest part of the script
		chattr +i $SHA_SUM/init/SHA_SUMS
	else
		if [ "$FIRST_RUN" != "no" ]
			then
				chattr -i $SHA_SUM/init/SHA_SUMS
				cat /dev/null > $SHA_SUM/init/SHA_SUMS
				{
					sha512sum $SHA512
					sha512sum $0
					sha512sum /bin/bash
					sha512sum $ANTIVIR
					sha512sum /usr/bin/freshclam
					sha512sum $ROOTKIT_CHECKER
					sha512sum $SECURITY_CHECKER
					sha512sum /bin/rpm			
				} >> $SHA_SUM/init/SHA_SUMS
		
				chattr +i $SHA_SUM/init/SHA_SUMS
				echo -e '\E[32mall ok'; tput sgr0
			else
				SUMS=$(sha512sum -c $SHA_SUM/init/SHA_SUMS)
					for sum in ${SUMS[@]}
						do
							if [[ "$sum"  == "FEHLSCHLAG" || "$sum" == "FAILED" ]]
								then
									echo  -e '\E[33mwarning:'; tput sgr0
									echo "at least one invalid checksum found"
									echo "use -f if you just updated your system"
									exit 1
							fi
						done
				echo -e '\E[32mall ok'; tput sgr0
		fi
fi	
}
###Each action has its own function ends here


#do the main action including check for dirs and files
main()
{
#select special features		
if [ ! -z $WITH_FEATURE ]
	then
		echo $INDEX >> $LOGFILE
		echo "file was created by $0" >> $LOGFILE
		echo "-----------------------------------------------------------------" >> $LOGFILE
		for feature in ${WITH_FEATURE[@]}
			do
				case $feature in
					A) check_antivir
					;;
					C) check_rootkit_checker
					;;
					D) check_smartctl
					;;
					S) check_lynis
				esac
			done
		self_test
		
		for feature in ${WITH_FEATURE[@]}
			do
				case $feature in
					A) virus_scan
					;;
					C) 
						if [ "$USE_QUIET" != "no" ]
							then
								{
									echo "with chkrootkit" 
									CNT=`$ROOTKIT_CHECKER -c --novl --nocolors -sk --nolog`
									echo "$CNT"		
								}>> $LOGFILE
							else
									{
									echo "with chkrootkit"
									CNT=`$ROOTKIT_CHECKER -c --novl --nocolors -sk --nolog`
									echo "$CNT"		
								}|tee -a $LOGFILE
						fi
					;;
					D)
						if [ "$USE_QUIET" != "no" ]
							then
								{
									echo "with smartmontools"
									disk_check
								} >> $LOGFILE
							else
								{
									echo "with smartmontools"
									disk_check
								} |tee -a $LOGFILE
						fi
					;;
					S)
						if [ "$USE_QUIET" != "no" ]
							then
								{			
									echo "with lynis"
									SNT=`$SECURITY_CHECKER -c -Q --no-colors --no-log`
									echo "$SNT"      
								}>> $LOGFILE
							else
								{			
									echo "with lynis"
									SNT=`$SECURITY_CHECKER -c -Q --no-colors --no-log`
									echo "$SNT"      
								}|tee -a $LOGFILE
						fi
					;;
					P)
						if [ "$USE_QUIET" != "no" ]
							then
								{
									verify_package
								}>> $LOGFILE
							else
								{
									verify_package
								}|tee -a $LOGFILE
						fi
					;;
					U) :
					;;
					\?) 
						option_h #in case the option dont met display help
				esac
			done
		echo "------------------------------------------------------------------" >> $LOGFILE
#with all features
	else
		if [ "$USE_QUIET" != "no" ]
			then
				{
					echo $INDEX
					echo "file was created by $0"
					echo "-----------------------------------------------------------------"
					echo "with clamscan"
					echo "with chkrootkit"
					echo "with lynis"
					check_antivir
					check_lynis 
					check_rootkit_checker
					check_smartctl
				}>> $LOGFILE
				self_test
			else
					{
					echo $INDEX
					echo "file was created by $0"
					echo "-----------------------------------------------------------------"
					echo "with clamscan"
					echo "with chkrootkit"
					echo "with lynis"
					check_antivir
					check_lynis 
					check_rootkit_checker
				}|tee -a $LOGFILE
				self_test
		fi
				virus_scan
		
		if [ "$USE_QUIET" != "no" ]
			then
				{
					CNT=`$ROOTKIT_CHECKER -c --novl --nocolors -sk --nolog`
					echo "$CNT"		
					disk_check
					SNT=`$SECURITY_CHECKER -c -Q --no-colors --no-log`
					echo "$SNT"
		
					verify_package	

					echo "------------------------------------------------------------------"

				} >> $LOGFILE
			else
						{
					CNT=`$ROOTKIT_CHECKER -c --novl --nocolors -sk --nolog`
					echo "$CNT"
					disk_check		
					SNT=`$SECURITY_CHECKER -c -Q --no-colors --no-log`
					echo "$SNT"
		
					verify_package	

					echo "------------------------------------------------------------------"

				}|tee -a $LOGFILE
		fi
fi
}	

drop_failure ()
{
echo -e '\t \t \t \t \E[31mfailure'; tput sgr0
}

drop_ok ()
{
echo -e '\t \t \t \t \E[32mok'; tput sgr0
}

we_fail()
{
echo -e '\t \t \t \t \E[31mfailed'; tput sgr0	
echo -e '\t \t \t \t \E[31mstop'; tput sgr0
exit 1
}

check_root

exit 0


##Todo:
#use more comments
#clean up the code
#colorize output
#aide check and encrypt 
#use -u to udated aide database
#verify package is kind of broken
#rkhunter check for updates to be more reliable
#rkhunter first initilise database if not present yet
#selftests: look up if the binarys which being used are valid or have been changed
#need the sourcerpm of rkhunter to implement selfupdate
#if package has fatal error reinstall it
#if rpm is not installed dont calculate checksum for program rpm
##dropped: we dont cover others than rpms in the moment
#if rkhunter database is not created creta this first. use rkhunter --proupd in an f statement to do this
#test whether packages match if not install them
#use aide to prevent filesystem infiltration
#check for both rkhunter and chkrootkit
#implement all stuff in a nicer interface
#if no network is present clamscan tries to update takes to long
#if no package manager is present try to build form scratch
#use extra functions for every function in the script
#implement file-integrety checker
#it mitght also be usefull to create additional logfiles  

#aoutosectools: (maybe should replace lynis in future)
#crypt hash grub randomly
#set ntp damon
#disable not needed services
#find and uninstall not needed compilers
#find and disabe account with weak passwords #howto do this
#disable not valid shells in /etc/shells
#setting kernel options according to lynis
